---
title: "lab_8"
author: "Yijun Cheng & Claire Guidinger"
date: "11/10/2021"
output: pdf_document
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      message = FALSE, 
                      warning = FALSE,
                      fig.width = 6.5, 
                      fig.height = 8)
library(tidyverse)
library(rio)
library(janitor)
library(dplyr)
library(here)
```




```{r commit1}
star <- import(here("data", "star.csv"))
star <- star %>% 
  clean_names()
```

```{r commit2}
#Bibliography
```


Here are my citations: @barnett2001body, @braun1999more, @kelly2018perceptions, @lavender2017men. I used the @tidyverse and @rio packages.

\newpage

# References

```{r commit3}
star %>% 
  group_by(sex, frl) %>% 
  summarize(math_mean = mean(tmathss), math_sd = sd(tmathss),
         rdg_mean = mean(treadss), rdg_sd = sd(treadss)) %>%
  select(sex, frl, math_mean, math_sd, rdg_mean, rdg_sd) %>% 
  as.tibble()
  
```

```{r commit4}
star %>% 
  group_by(frl) %>% 
  ggplot(aes(totexp, tmathss))+
  geom_point()+
  geom_smooth(method = "lm", aes(color = frl)) +
  labs(
    title = "Relation between teacher experiences and math scores",
    subtitle = "Separate regrression lines displayed by free/reduced price lunch status",
    x = "Teacher Experience (years)", 
    y = "Total Math Sacle Score",
    color = "Lunch status"
    ) +
  theme_minimal()+
theme(legend.position="bottom", legend.box = "horizontal")

    

```

